### ISSUE TITLE
short speech recognition

### ISSUE THREAD

**Issue by Stverib** [Adri6336/gpt-voice-conversation-chatbot#23]
When I press and hold space and start speaking, once I pause and start thinking about how to speak, soon, the conversation mode will be closed and the conversation will be submitted to chatgpt. This is very unnatural, shouldn't it wait for the user to release the space before handing over what the user said to chatgpt? Just a little advice. I like your project, but there do exist some problems.

**Comment by Adri6336** [comment]
Sorry for the super late response! That issue has been fixed
