### ISSUE TITLE
processing time of prompts is really long

### ISSUE THREAD

**Issue by shadowdoggie** [Adri6336/gpt-voice-conversation-chatbot#3]
Hello Adri6336 :D 

I absolutely love your program, it includes everything i want pretty much, but the processing time of a prompt takes about 5 seconds every time.

Is there anything you can do to improve this delay?

Also, is there any way to choose a elevenlabs voice?

tyvm in advance!

**Comment by Adri6336** [comment]
Heyo, I'm super happy to hear you're liking it so far! :D

Unfortunately I won't be able to greatly affect any delays in communication. Every message has to be sent to OpenAI, so their responsivity is the first thing to determine speed in both the CLI and voice-chat versions. Additionally if you're using the voice-chat version, your speech must be interpreted by Google speech to text services. Then finally, if you're using the voice-chat version or the CLI spoken mode, the text will be spoken by Elevenlabs or Google TTS. The side effect of this is that a speedy conversation relies on all the 3rd party services being up and responsive.

The best way to speed up conversations would be to limit connections to OpenAI only. To do this, you can run the gptcli.py script, then enter '!robospeak()'. You'll loose the ability to speak with your voice, but you'll still be able to hear the responses and it should be slightly faster.

The ability to switch voices is something I can affect though! This is definitely something I want to add soon. Things keep coming up, so I keep delaying it in favor of other changes lol, but I def do plan to add it. 

I really appreciate your feedback yo!
