### ISSUE TITLE
Custom ElevenLab Voices

### ISSUE THREAD

**Issue by EllangoK** [Adri6336/gpt-voice-conversation-chatbot#4]
Mentioned in #1, but I do want to use a custom voice.

https://github.com/Adri6336/gpt-voice-conversation-chatbot/blob/253a4640631acd456aa51e5a3d0376826e97c823/tts_functions.py#L44

Its actually pretty simple, if the user knows their voice ID which they can query the endpoint themselves for, they just swap EXAVITQu4vr4xnSDxMaL` with it. This works.

I could probably submit a PR for it myself, but how should I pass it in? Do you perhaps want to use argparse to parse the args as it is a bit cleaner than checking the length of argv and assuming positions and the like.

Edit: I am going to try to do some refactoring in general if that is okay, as you have a bunch of duplicated code between gptcli and main.py.

**Comment by Adri6336** [comment]
Heyo, thanks for bringing this to my attention! :D

I've gotten a fair bit of your suggestion completed, but it's late where I'm at so imma hold off until tomorrow. For the most part I've got it coded using argparse (thx for the suggestion!) and moved that function I forgot about to the general functions file. I'm also now going to use argparse to allow for voice swapping for the time being.

I still have lots to learn with regards to Python, so your recommendation is legit super appreciated yo

**Comment by EllangoK** [comment]
No problem. And yeah, the elevenlabs limit gets hit quickly, while openais limits are so cheap. Hopefully someone releases a cheaper voice model website.

Did check it though and it does work, thanks!
